### ISSUE TITLE
The product is not added to the cart when multiple time slots are added to the cart but one of the time slot is not available

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Multiple-Time-Slot-addon#11]
For a product, there are 4 timeslots 7-8, 8-9, 9-10 and 10-11. Each time slot lockout is 5. For 25th Jan 7-8 time slot is booked for 3 qty. Then for the same date, I am trying to add 7-8 and 8-9 time slot to the cart for 5 qty. On clicking on Add to Cart I am getting the notice for the 7-8 timeslot that there are only 2 bookings available for the 7-8 timeslot, but the 8-9 timeslot is not added to the cart.

I think if a time slot is not available then the other one for which the bookings are available should be added to the cart.

**Comment by priyanka-tychesoftwares** [comment]
I think the current behavior is right. If the customer selects more than one timeslot that means he wants to book the product with those timeslots. So it is not right to add the product to the cart with only the available time slot. If it is fine for the customer to book another time slot then he can select other timeslots again and add them to the cart.

@ashokrane and @kartikparmar please let me know your opinion on this issue so I can take the necessary action on this one.

**Comment by ashokrane** [comment]
Yes, this behaviour is right @priyanka-tychesoftwares . We should give the message instead of adding to cart. Closing this one.
