### ISSUE TITLE
Getting Notices displayed on the cart page

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Multiple-Time-Slot-addon#12]
A product has recurring days and time slots. Multiple time slots addon is enabled and the product has Multiple option selected. On the product page, for a date 2 timeslots are selected and is added to the cart. On the cart page, there are some notices displayed and the time slots selected are not displayed. http://screencast.com/t/ruwnX7Yzv

**Comment by kartikparmar** [comment]
Unable to replicate in the latest git hence closing it.
