### ISSUE TITLE
The Order does not have the booking date and time slots

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Multiple-Time-Slot-addon#13]
When a product is added to the cart the booking date is there in the cart, the time slots are not added to the cart. Now when I try to place the order, the order received page does not have booking date or the time slot.

The email notification too does not have booking date or time slot. Nor the Edit order has any booking date or time slot.

Order #5296 
Order URL: http://staging.tychesoftwares.com/woo_khyati/wp-admin/post.php?post=5296&action=edit

**Comment by kartikparmar** [comment]
unable to replicate the issue in the git hence closing it.
