### ISSUE TITLE
The time slot price is coming as 0 when multi-currency is enabled

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Multiple-Time-Slot-addon#15]
For a product time, slot price is set to 0. So default product price will be applied to the time slot.
The product price is set to 100. And conversion is set to 10 times.

When the time slot is selected, on the product page the price is coming as 0.00 AED. And on the cart page, the price is coming as 1000 AED.

Product page: http://screencast.com/t/LYDwa9Jzr1W
Cart page: http://screencast.com/t/zinZjGTZ

**Comment by priyanka-tychesoftwares** [comment]
There is no client who uses the Multiple Timeslot Addon along with the Multi-currency feature so I am closing this issue.
