### ISSUE TITLE
The prices are not coming correctly with multi-currency

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Multiple-Time-Slot-addon#16]
For a product, there are 4 time slots: 
10:00 - 12:00; ₹ 150
13:30 - 14:30; ₹ 175
15:00 - 17:00 
18:00 - 20:00; ₹ 200 

The product price is set to 100. And conversion is set to 10 times.

When the time slot is selected, on the product page the price is coming as 1000+time slot price AED.

The price on the product page is coming correct, but on the cart page, the price is coming wrong. http://screencast.com/t/lacxWBmc

**Comment by priyanka-tychesoftwares** [comment]
There is no client who uses the Multiple Timeslot Addon along with the Multi-currency feature so I am closing this issue.
