### ISSUE TITLE
Give instruction about single multiple time slot in documentation

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Multiple-Time-Slot-addon#17]
In Multiple Time slot addon documentation give instruction regarding Single time slot also so it easy to see both types of time slot.

http://screencast.com/t/qJGU1Ls7oLt

http://screencast.com/t/dqERfNwcwNri

**Comment by priyanka-tychesoftwares** [comment]
I am closing this issue as we have mentioned the difference between Single and Multiple timeslots in our Multiple TimeSlot Addon documentation.
