### ISSUE TITLE
The time slot error message is coming wrong

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Multiple-Time-Slot-addon#19]
The error message when adding the product to cart for more than the available is coming as http://prntscr.com/e6x67q

Whereas the message should be of the format: 'For PRODUCT_NAME, the time TIME on DATE has been fully booked. Please try another timeslot.'

This is coming for products which have Multiple enabled in time slots.

**Comment by kartikparmar** [comment]
Unable to replicate the same in latest git hence closing it.
