### ISSUE TITLE
Able to add product to the cart for time slots more than available 

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Multiple-Time-Slot-addon#20]
I have multiple time slots enabled, the availability of the time slot is set to 30. I am able to add the product to cart for 31 qty for only one-time slot. Whereas there are only 30 availability.

Product URL: http://staging.tychesoftwares.com/woo_bkap_next_release/product/lawyers-appointment/?removed_item=1

Date: 24th Feb 
Time slot: 5pm-6pm

**Comment by kartikparmar** [comment]
Fixed in https://github.com/TycheSoftwares/woocommerce-booking-1.7/commit/e1015e847f73aa08a83a5ef0d4ad09fd86b6f9a8 hence closing it
