### ISSUE TITLE
Cart is showing empty even if the product is added to the cart.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/Multiple-Time-Slot-addon#21]
Product setup:
Simple product
Recurring Weekdays with timeslots
Advance Booking Period (in hours): 24

When clicking on "Add to cart" button the product is not getting added to the cart, the cart is showing as empty.
Please see this video: https://www.screencast.com/t/gfy8VerS70NH

**Comment by kartikparmar** [comment]
Unable to replicate in latest git copy hence closing it.
