### ISSUE TITLE
Time slot not display in proper way

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Multiple-Time-Slot-addon#23]
When i create three time slot 8:00 am to 9:00 am ,10:00 am to 11:00 am and 12:pm to 13:00pm now on front end it shows first 10;00 am to 11:00 am and then 8:00 am to 9:00 am which is wrong (this addon is enable)

https://www.screencast.com/t/S3SmdNHsO

**Comment by priyanka-tychesoftwares** [comment]
I am unable to replicate this issue now hence closing it.
