### ISSUE TITLE
The lockout message is coming wrong

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Multiple-Time-Slot-addon#24]
When multiple time slot setting is enabled, the availability of the time slot is 1 & 4. When trying to add the time slot for 5 qty, the lockout message is coming like this http://prntscr.com/eve9bq

Whereas when single time slot setting is selected, and the availability of the time slot is 4 and trying to add the time slot to cart for 5 qty, the lockout message is coming correctly: http://prntscr.com/eveafi

**Comment by kartikparmar** [comment]
fixed in https://github.com/TycheSoftwares/Multiple-Time-Slot-addon/commit/26d75cbf2f6aa0176dfe51b0630ffa5f96d9833a hence closing it.
