### ISSUE TITLE
Only shows first attributes availability on product page with multiple time slot is enable.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Multiple-Time-Slot-addon#25]
When i am doing attributes lockout with recurring days with time slot then  on product page it shows only first attributes availability with multiple time slot is added

https://www.screencast.com/t/6lD55nDlUwm

And when i am enable single time slot  then it shows properly.

https://www.screencast.com/t/pTbUgplkyydW

**Comment by priyanka-tychesoftwares** [comment]
This is working fine now hence closing this issue.
