### ISSUE TITLE
Grouped product totals show 0 when Multiple time slot addon is active

### ISSUE THREAD

**Issue by ashokrane** [TycheSoftwares/Multiple-Time-Slot-addon#27]
Grouped product totals show 0 when Multiple time slot addon is active. The totals appear fine when the Multiple Time slots addon is deactivated.

This issue is added from plugin repo to here: https://github.com/TycheSoftwares/woocommerce-booking-1.7/issues/937 .

**Comment by priyanka-tychesoftwares** [comment]
The Grouped price is being calculated correctly when one of the timeslots is selected. But the loader keeps loading when more than one timeslot is selected. https://www.screencast.com/t/mHoj7bQkr1

**Comment by ashokrane** [comment]
@priyanka-tychesoftwares  Is this reported by a client? (The issue regarding the loader)

**Comment by priyanka-tychesoftwares** [comment]
@ashokrane No, this loader issue is not reported by any client. I got this issue when testing the main issue. I am closing this as there is no one come up with such an issue.
