### ISSUE TITLE
Error message is displayed on the front-end of the product page when over quantity is added to the cart

### ISSUE THREAD

**Issue by shettyshruti** [TycheSoftwares/Multiple-Time-Slot-addon#28]
Product type: Simple product
Booking type: Date & Time
Timeslots: 10:00 am to 11:00 am and 11:00 am to 12:00 am.
Maximum booking for each timeslot is 2.

On front-end, the quantity selector allows adding the quantity to 4 for single timeslot selected whereas there are only 2 booking available for each timeslot. When I click on Add to Cart button the notice appears saying there is no availability and the below error message are being displayed on the product page.
Notice: Undefined index: book.limited-booking-msg1 in /home/tychesod/public_html/staging/woo_shruti/wp-content/plugins/woocommerce-booking/lang.php on line 54
Notice: Undefined index: book.limited-booking-msg2 in /home/tychesod/public_html/staging/woo_shruti/wp-content/plugins/woocommerce-booking/lang.php on line 54

Screenshot: https://www.screencast.com/t/jzPhZwXEqk4

**Comment by kartikparmar** [comment]
Fixed in https://github.com/TycheSoftwares/Multiple-Time-Slot-addon/commit/26d75cbf2f6aa0176dfe51b0630ffa5f96d9833a commit hence closing it.
