### ISSUE TITLE
The cart page shows "0" amount if i am not selecting timeslot for that product

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Multiple-Time-Slot-addon#30]
I set multiple time slot for time slot price 
while selecting booking date only then cart page shows "0" amount and Add To Cart button is shows active

https://www.screencast.com/t/xIdjzkTHj1e
on global setting page disable this setting "Always display the Add to Cart and Quantity buttons:"

**Comment by kartikparmar** [comment]
Unable to replicate in the latest git hence closing it.
