### ISSUE TITLE
Exported Booking is showing the time as 00:00 in Google Calendar

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/Multiple-Time-Slot-addon#31]
Product setup:
Variable product
Date & Time booking type
Screenshot: https://www.screencast.com/t/qxIyu1328G
Time Slot Selection: Multiple

I have placed an order for date 20th January 2017 for a time 10:00-11:00. This booking is exported to Google calendar and showing a time as 00:00 - 11:00.
Screenshot: https://www.screencast.com/t/qxIyu1328G

Placed another order for date 21st Jan 2018 for timeslots 09:00 - 10:00 and 10:00 - 11:00. Exported Booking is showing the booking time as 00:00 in Google calendar.

**Comment by kartikparmar** [comment]
Fixed in https://github.com/TycheSoftwares/woocommerce-booking-1.7/issues/2207
