### ISSUE TITLE
The Timeslots are not getting updated when we reschedule them from "Edit Bookings" option on the My Account page

### ISSUE THREAD

**Issue by upenkapse** [TycheSoftwares/Multiple-Time-Slot-addon#32]
Steps to replicate the issue:
1. Create a Date & Time-based product with Multiple Timeslots enabled as shown in this screenshot:
https://www.screencast.com/t/IHTeStI8yQK5
2. Place a booking by selecting multiple timeslots as shown in this screenshot:
https://www.screencast.com/t/FPmZtJPKRZ8

Issue: The booking will not appear under the View Bookings section as reported here: https://github.com/TycheSoftwares/Multiple-Time-Slot-addon/issues/29

And also when the customer tries to reschedule the timeslots from the Edit Bookings link on My Account page it does not work:
https://www.screencast.com/t/sYrfFevGG
https://www.screencast.com/t/AAZNpouZJy1p

Ticket Link: https://tychesoftwares.freshdesk.com/a/tickets/1816

**Comment by kartikparmar** [comment]
Fixed in https://github.com/TycheSoftwares/woocommerce-booking-1.7/pull/2842/commits/eb09fc7bb2430f8fe7cb03a038ef0f2ad27bc4ad commit.
