### ISSUE TITLE
End time of the second timeslot is not displaying on the Order received page and in the emails when the multiple timeslots selected for the booking.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/Multiple-Time-Slot-addon#33]
Product setup: simple product
booking type: Date & Time - Fixed Time
Enable Inline Calendar option is enabled.
Maximum Bookings for the date are set to 14 and for the timeslot is set to 1.
Time Slot Selection: Multiple
Availability tab settings: https://www.screencast.com/t/WSR6iL4K  
https://www.screencast.com/t/oMYdXjwR

I have added the multiple bookings in the Cart and placed a single order for them. The end time of the second timeslot is not displaying on the order received page, and in the emails.
screenshot of the issue: https://www.screencast.com/t/zLnDf6h7rEU

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/5001

**Comment by kartikparmar** [comment]
Fixed in https://github.com/TycheSoftwares/woocommerce-booking-1.7/commit/151a1d20e2c7a06118a0288b564684ab04563862 commit hence closing it.
