### ISSUE TITLE
Edit Order link should shows all time slot link

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Multiple-Time-Slot-addon#35]
Place an order for Fixed date and time slot product, select more than 1-time slot
Go to Edit Order page --> Edit Booking page and I was able to see only 1 latest time slot with booking price

https://www.screencast.com/t/aD9lY8wo
https://www.screencast.com/t/BhTa672Jb

I think we should display all time slot to the edit booking page

Note: On View Booking page, It shows both bookings with the respective time slot.

**Comment by kartikparmar** [comment]
Fixed in https://github.com/TycheSoftwares/woocommerce-booking-1.7/commit/e1015e847f73aa08a83a5ef0d4ad09fd86b6f9a8 commit hence closing it.
