### ISSUE TITLE
The booking price is not calculated properly and showing 1 instead of double the price when multiple time slot is selected on product page

### ISSUE THREAD

**Issue by komal-maru** [TycheSoftwares/Multiple-Time-Slot-addon#37]
The booking price is not calculated properly and showing 1 instead of double the price when multiple time slot is selected on product page

Ticket: https://tychesoftwares.freshdesk.com/a/tickets/9308

Settings: https://www.screencast.com/t/Vu33IvC1HB , https://www.screencast.com/t/lLPaPFH6Sp

Video: https://www.screencast.com/t/YowTe7We4

**Comment by kartikparmar** [comment]
fixed in https://github.com/TycheSoftwares/woocommerce-booking-1.7/commit/392ef4418b06f1dc639a62654f5150dcbcd6d44f commit hence closing it.
