### ISSUE TITLE
Unable to edit the booking order.

### ISSUE THREAD

**Issue by komal-maru** [TycheSoftwares/Multiple-Time-Slot-addon#39]
Unable to Edit the order where the multiple time slot addon is enabled in the Edit Booking page.

Order: https://prnt.sc/oqtx6d 

Edit booking order: https://prnt.sc/oqtxdw - here the selected time slot is not shown. 

And when tried to change it, it will show the error: https://prnt.sc/oquak0

On client site, ajax in the timeslot field in the 'Click to edit booking' is loading continuously

Ticket: https://tychesoftwares.freshdesk.com/a/tickets/9359

**Comment by kartikparmar** [comment]
Duplicate issue hence closing it. https://github.com/TycheSoftwares/Multiple-Time-Slot-addon/issues/46
