### ISSUE TITLE
Availability of time slot not displayed

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Multiple-Time-Slot-addon#4]
The availability of the time slot is not displayed when multiple time slots are seletced. http://screencast.com/t/tqswm4jwKzLc

Product url: http://staging.tychesoftwares.com/woo_khyati3/?product=appointment-with-a-dietician

**Comment by priyanka-tychesoftwares** [comment]
The availability of timeslots will not be displayed when selected multiple timeslots. And none of our clients asked for this. Hence I am closing this issue.
