### ISSUE TITLE
Overbooking is possible when any new date from the calendar which is not selected any time and added to the cart.

### ISSUE THREAD

**Issue by komal-maru** [TycheSoftwares/Multiple-Time-Slot-addon#41]
Overbooking is possible when any new date from the calendar which is not selected any time and added to the cart.

I have added, time slots for different lockouts say 5, when I select the time slot and add the quantity to 10 for a new date then it is not giving an error message from our plugin and able to place the order

Settings: https://prnt.sc/oqui6i , https://prnt.sc/oquib7 , https://prnt.sc/oquif9 , https://prnt.sc/oquiix

[bkap-multiple-time-slot.zip](https://github.com/TycheSoftwares/Multiple-Time-Slot-addon/files/3488659/bkap-multiple-time-slot.zip)

[woocommerce-booking.zip](https://github.com/TycheSoftwares/Multiple-Time-Slot-addon/files/3488709/woocommerce-booking.zip)

**Comment by kartikparmar** [comment]
Fixed in https://github.com/TycheSoftwares/woocommerce-booking-1.7/commit/e1015e847f73aa08a83a5ef0d4ad09fd86b6f9a8 commit hence closing it.
