### ISSUE TITLE
Edit booking is not working on cart page and checkout page

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Multiple-Time-Slot-addon#44]
Edit booking is not working on cart page and checkout page

see the video for better understanding : 
https://www.screencast.com/t/vvxjMpYPws

**Comment by apeksha10** [comment]
Edit booking post is also not working 
https://www.screencast.com/t/ofB277cmeW

**Comment by kartikparmar** [comment]
I have committed the code for the Cart and Checkout page Edit Booking. Edit Booking page still has the issue of prepopulating the booked timeslot which can be fixed in the next version so @apeksha10 please add it as new issue with next version.
