### ISSUE TITLE
Price is not updating properly on increasing the quantity when Multiple time slot addon is active 

### ISSUE THREAD

**Issue by Dhara61** [TycheSoftwares/Multiple-Time-Slot-addon#49]
Price is not updating properly on increasing the quantity when Multiple time slot addon is active  

Steps: 

1. Enable Booking and Multiple time slot addon
2. Set the product price to 50 
3. Enable the booking settings as shown in these screenshots: http://prntscr.com/pjzzyi , http://prntscr.com/pk00dh , http://prntscr.com/pk00hx 
4. Product settings: http://prntscr.com/pk00s3 

Now on the frontend when 1 quantity is there then 50 is coming which is fine but when I increase the quantity to 2 then instead of 100 it is becoming 200. For 3, 400 price is coming and so on.

Ticket URL: https://tychesoftwares.freshdesk.com/a/tickets/10482

**Comment by Dhara61** [comment]
One more client reported this issue: https://tychesoftwares.freshdesk.com/a/tickets/11096

**Comment by kartikparmar** [comment]
Soln: https://prnt.sc/uhmjwn

**Comment by kartikparmar** [comment]
Unable to replicate the issue with the latest GIT copy hence closing it.
