### ISSUE TITLE
An error message "Booking is not available for selected quantity" displaying on the product page.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/Multiple-Time-Slot-addon#52]
**Describe the bug**
An error message "Booking is not available for selected quantity" displaying on the product page.

**To Reproduce**
1. Keep the Multiple Timeslot Addon as active. And create a product with a Fixed time booking type and add a one-time slot to it.
2. You will see the error message on the front-end of the product.

**Screenshots or Video**
https://www.screencast.com/t/rn0lZ9nBm0y5

**Isolating the problem (mark completed items with an [x]):**
- [] This bug happens with only Booking & Appointment Plugin for WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront]
- [x] I can reproduce this bug consistently using the steps above

https://tychesoftwares.freshdesk.com/a/tickets/21704

**Comment by kartikparmar** [comment]
Fixed in https://github.com/TycheSoftwares/woocommerce-booking/pull/4006/commits/6a0239c8bb1aa48250e4e4bb984521cbb737c9c0 commit hence closing it.
