### ISSUE TITLE
Timeslots are displaying in the dropdown form instead of displaying with checkboxes on the product page.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/Multiple-Time-Slot-addon#55]
**Describe the bug**
Timeslots are displaying in the dropdown form instead of displaying with checkboxes on the product page. This is not allowing to select multiple timeslots at a time even if the Time Slot Selection is selected as "Multiple".
I found this issue while testing this issue: https://github.com/TycheSoftwares/woocommerce-booking/issues/4104

**To Reproduce**
1. Create a product with a Fixed time booking type and add the timeslots. (You should have the latest v5.9.1 of Booking plugin and v2.5 of Multiple Timeslot Addon while checking this issue.)
2. Select the "Time Slot Selection" as "Multiple".
3. You will see that the timeslots are displaying in the dropdown form instead of checkboxes. So the user cannot select multiple timeslots at a time.

**Expected behavior**
Multiple timeslots should list with the checkboxes that allow selecting multiple timeslots together.

**Screenshots**
https://www.screencast.com/t/Ce8BUs01Tn
https://www.screencast.com/t/Wnrh7mpDNlg

**Comment by handelce** [comment]
@priyanka-tychesoftwares I'm unable to replicate this issue. See steps I took below:

1. Installed Booking Plugin v5.9.1 and Multiple Add on plugin v2.5. See screenchot: https://www.awesomescreenshot.com/image/13172171?key=45d1a348d2497c4fb2a8d43a9083247f
2. Created a product with Fixed Time booking: https://www.awesomescreenshot.com/image/13172060?key=832662ca76542f12ecd5afcca0313e87. 
3. Selected "Time Slot Selection" as "Multiple" and added time slots: https://www.awesomescreenshot.com/image/13172094?key=9410460680c73edd9faaf5f53d81ea40
4. Timslots are displaying as checkboxes: https://www.awesomescreenshot.com/image/13172225?key=c55572b3eb2e58f6d7a2ebbfeaee4354

Here is a video of my implementation: https://www.awesomescreenshot.com/video/5157092?key=400b35f08ea0f44ec69da7f1efe8ae1b

**Comment by priyanka-tychesoftwares** [comment]
I tried to replicate this issue with the current versions and I am also unable to replicate the same. Hence closing this issue.
