### ISSUE TITLE
 The 'Add to Cart' button does not enable upon selecting multiple time slots and even the price is not calculated based on the selected time slots.

### ISSUE THREAD

**Issue by komal-maru** [TycheSoftwares/Multiple-Time-Slot-addon#60]
**Describe the bug**
The 'Add to Cart' button does not enable upon selecting multiple time slots and even the price is not calculated based on the selected time slots.

Tested with WooCommerce 8.9.3, BKAP 6.3.0, Multiple Time Slot Addon 2.8.0

**To Reproduce**
1. Create a Simple product with a Fixed Time booking type where the Inline Calendar is enabled: https://prnt.sc/i2DNQ7RdJ6CE
2. Set 'Time Slot Selection' to Multiple.
3. Set a Time slot in the range of 30 mins with a Maximum Booking set to 1, and price to 5: https://prnt.sc/nrriFmNyk9aF
4. Now, select multiple time slots on the product page and see the error, the 'Add to Cart' button is not enabled, and the booking price is not calculated as per the selected time slots. Screenshot: https://prnt.sc/o7vOAvjDMU_X

**Expected behavior**
the 'Add to Cart' button should be enabled after the selection of time slots and price calculation, and the booking price should calculated fine as per the selected time slots.

**Additional context**
Ticket: https://support.tychesoftwares.com/conversation/2569?folder_id=13

**Comment by komal-maru** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #60](https://trello.com/c/BvmHDqS1/132-issue-60)

**Comment by kartikparmar** [comment]
This issue is fixed in https://github.com/TycheSoftwares/woocommerce-booking/pull/5970/commits/b04d4a86a316f7cebefe78206c56f52cafc47537 commit hence closing it.
